[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

[rpc_endpoints]
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
base_sepolia = "https://sepolia.base.org"
eth_sepolia = "https://sepolia.drpc.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
